### ISSUE TITLE
Cannot open file for read

### ISSUE THREAD

**Issue by sroforsolya** [leon/docker-gltf-to-udsz#3]
Hello,
I get the following error when I try to run start.sh with the model provided in the example folder. 

ERROR: Cannot open file for read: examples/exterior.glb [GLTF_ERROR_IO_OPEN_READ]

I tried with other models, same result. Any ideas what might be the cause of this? Thank you!

**Comment by leon** [comment]
It didn't want to work when you specified the output file in another directory.

```
./start.sh examples/exterior.glb
```

this will work.
