### ISSUE TITLE
Support batch conversion

### ISSUE THREAD

**Issue by SidharthRaveendran** [leon/docker-gltf-to-udsz#4]
How do we do batch conversions using this image?

**Comment by leon** [comment]
I've added a batch script for you.

What it does is it launches the docker image, then it passes along a for loop to the image, where it finds all the .glb files in the directory where the command is run.

So simply place all your .glb files in a folder.
navigate to that folder in the terminal.
then drag the batch.sh file to the terminal which should add the full path to the batch.sh file
then press enter to execute it.
it will output a Processing $file
and then 
Done.

Hope this helps :)
